### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: socket hang up

### ISSUE THREAD

**Issue by hubitor** [yujiosaka/headless-chrome-crawler#358] opened 2019-11-21 09:15 UTC
**What is the current behavior?**
I'm getting following error during start:

```
(node:1008440) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1008440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1008440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and the app is exiting immediately.

**If the current behavior is a bug, please provide the steps to reproduce**

1. Use the example from Usage.
2. Start app:

`$ node index.js`

**What is the expected behavior?**
No error...

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Version: 1.8.0
- Platform / OS version: Arch Linux
- Node.js version: 10.16.1

**Comment by kulikalov** [comment] 2020-10-17 06:39
Hey @hubitor! I've just tested the example with the latest version of this library. Assuming, it's the same version you've been using, since it wasn't updated since 2018. Could you post the code you are trying to run? From the import statement till the very last line.

**Comment by kulikalov** [comment] 2020-10-17 06:40
closing for now, since it was a while and the issue is not reproducible at the moment.

**Closed by kulikalov** 2020-10-17 06:40 UTC

**Comment by ndom91** [comment] 2022-04-23 14:00
Having this same issue on Arch Linux :thinking: 

`node`: 14, 16, 18
`headless-chrome-crawler`: 1.8

Immediately after launch:

![image](https://user-images.githubusercontent.com/7415984/164909189-c0f31ad0-2d9b-48d4-9160-b9d59705cff2.png)

My code: 
```js
const HCCrawler = require('headless-chrome-crawler')
const fs = require('fs/promises')

const SEARCH_TERM = 'berlin'

const main = async () => {
  try {
    // sites.txt is just a newline delimited list of URLs
    const file = await fs.readFile('sites.txt', 'utf8')
    const crawler = await HCCrawler.launch({
      maxConcurrency: 5,
      // Function to be evaluated in browsers
      evaluatePage: (() => {
        // eslint-disable-next-line no-undef
        if ($('body').text().includes(SEARCH_TERM)) {
          return {
            url: document.location.href,
            title: document.title,
          }
        }
      }),
      // Function to be called with evaluated results from browsers
      onSuccess: (async ({ result, links }) => {
        console.log(result);
        console.log(links);
        // await crawler.queue(links)
      }),
    });
    const sites = file.split('\n')

    for (const site of sites) {
      await crawler.queue(site)
    }
    // await crawler.queue();
    await crawler.onIdle();
    await crawler.close();
  } catch (e) {
    console.error(e)
  }
}

main()
```
