### ISSUE TITLE
how to download use crawler for download HTML files?

### ISSUE THREAD

**Issue by lx171717** [yujiosaka/headless-chrome-crawler#164] opened 2018-03-20 03:11 UTC
for example, 
input:
url1=> http://www.google.com
url2=>http://www.bing.com
...
urlN=>http://www.N.com
output:
url1.html
url2.html
..
urlN.html

Could you  tip some sample code ? thanks very much.

**Comment by BubuAnabelas** [comment] 2018-03-20 05:06
You'd have to use the [`newpage`](https://github.com/yujiosaka/headless-chrome-crawler#event-newpage) event and save the [page content](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecontent) like this:

```javascript
const HCCrawler = require('headless-chrome-crawler')
const fs = require('fs')

const run = async () => {
  const crawler = await HCCrawler.launch()

  crawler.on('newpage', async page => {
    const html = await page.content()

    fs.readFileSync('./example.com',)
  })

  crawler.queue('https://example.com/')

  crawler.onIdle().then(() => crawler.close())
}

run()
```

**Comment by yujiosaka** [comment] 2018-03-21 19:14
Closing this in favor of @BubuAnabelas 's answer.
Please reopen this issue if the problem is not solved.

**Closed by yujiosaka** 2018-03-21 19:14 UTC
Labels: question

**Comment by lx171717** [comment] 2018-03-22 02:21
@BubuAnabelas @yujiosaka  Thanks very much for your reply

**Comment by lx171717** [comment] 2018-03-22 02:28
@BubuAnabelas I try above code  but output html content is  empty .
"<html><head></head><body></body></html>"

**Comment by BubuAnabelas** [comment] 2018-03-22 04:16
@lx171717 You're right, you should try accessing the page content and write it to a file once the [DOMContentLoaded](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-domcontentloaded) or [load](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-load) events are fired.

**Comment by lx171717** [comment] 2018-03-23 02:19
Thanks very much , Could you supply some sample  code of the  DOMContentLoaded are fired?
