### ISSUE TITLE
I'm having trouble working with the `evaluatePage` option

### ISSUE THREAD

**Issue by brianzhou13** [yujiosaka/headless-chrome-crawler#231] opened 2018-05-03 03:09 UTC
**What is the current behavior?
I'm having difficulty finding a way to get the text of the scraped page.

**If the current behavior is a bug, please provide the steps to reproduce**
not a bug -- just a question.

**What is the expected behavior?**
being able to get the text from `evaluatePage` ... but I don't see it being executed.

**What is the motivation / use case for changing the behavior?**
n/a

**Please tell us about your environment:**

- Version:^1.6.0
- Platform / OS version: high sierra / v10.13.4
- Node.js version:  │v9.10.1

**Comment by brianzhou13** [comment] 2018-05-08 01:25
bump if you happen to know -- @yujiosaka  thanks again!

**Comment by BubuAnabelas** [comment] 2018-05-08 02:07
You have to pass the [selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) which you want to get from the HTML Document to the evaluatePage function.
In the example above you are getting just the `<title>` text from the HTML Document.
You could get the body or any other tag/selector just by doing the same as with the title.

**Comment by OmarJAH** [comment] 2018-05-08 16:06
If you need the full html you can go with this:

```javascript
evaluatePage: (() => ({
    content: $('html').html()
})),
```

This will lead to the html code being saved in the "result.result.content" part of the overall "result" object, which you can use inside the onSuccess function:

```javascript
onSuccess: (result => {
     console.log(JSON.stringify(result.result.content, null, 2));
     doAnalysisOnDynamicSourceCode(result.result.content);
 }),
```

**Comment by brianzhou13** [comment] 2018-05-08 16:25
Yeah -- this simple solution kinda dawned on me late last night before bed.... I'm an idiot.

I'll give it a crack tonight.

**Comment by yujiosaka** [comment] 2018-05-10 13:12
@BubuAnabelas @OmarJAH
Thank you guys for your help!

@brianzhou13 
Also thank you for asking a question!
I tend to be slow replying, but I'd like to answer any kind of question!

**Comment by yujiosaka** [comment] 2018-06-10 06:03
Closing this issue assuming that the problem is solved already

**Closed by yujiosaka** 2018-06-10 06:03 UTC
Labels: question
