### ISSUE TITLE
crawler.response becomes null when connecting to specific chrome instance 

### ISSUE THREAD

**Issue by carlkentor** [yujiosaka/headless-chrome-crawler#354] opened 2019-09-19 22:31 UTC
**What is the current behavior?**
Okay, I dont know if this should be classified as a bug or not. But since I cant seem to find any trace of this in the docs, here it is. 

When connecting to a specific chrome instance through the: 
 `await HCCrawler.connect({
    browserWSEndpoint: wsChromeEndpointurl, 
    ...more options goes here})`  method, the call to `await crawl()` results in a null response. 
 The issue lies within: 

> \node_modules\headless-chrome-crawler\lib\crawler.js

    async crawl(){
    await this._prepare();
    const response = await this._request(); //1. Results in Null
	console.log(response); //2. ======> NULL INDEED
    await this._waitFor();
    const [
      result,
      screenshot,
      cookies,
      links,
    ] = await Promise.all([
      this._scrape(),
      this._screenshot(),
      this._getCookies(),
      this._collectLinks(response.url),  //3. ====> Exception gets thrown here 
    ]);
    return {
      options: this._options,
      depth: this._depth,
      previousUrl: this._previousUrl,
      response: this._reduceResponse(response),
      redirectChain: this._getRedirectChain(response),
      result,
      screenshot,
      cookies,
      links,
    }; }
`

**Steps to reproduce**

1.  Close all chrome instances. 
2. Open CMD and run the following to start Chrome with remote debugging enabled:  

> start chrome.exe --remote-debugging-port=9222
3. Navigate to http://localhost:9222/json/version and copy the value of "webSocketDebuggerUrl"
4. Set the browserWSEndpoint to the value you just copied. 

**What is the expected behavior?**
When running through a clean instance with the 
```
await HCCrawler.launch({
    ...options
})
```

command, everything works fineand the result comes back as expected. 
What am I missing here?  

**Please tell us about your environment:**

- Version: 1.8.0
- Platform / OS version: Windows 10  / 1803 
- Node.js version: v10.16.3

**Comment by simlevesque** [comment] 2019-09-23 22:03
I have the same error

**Comment by simlevesque** [comment] 2019-09-24 16:10
Hi @carlkentor , I've made a fork of the project with updated dependencies and a fix that I found in Puppeteer's issues (https://github.com/GoogleChrome/puppeteer/issues/2479#issuecomment-408263504) that seems to fix the issue on my end.

I've also made a issue in Puppeteer because they seem to be the cause of the problem: https://github.com/GoogleChrome/puppeteer/issues/4970

Could you please tell me more about your setup ? Are you using docker ? And could you try my fork ?

To use the fork, change your package.json like this: `"headless-chrome-crawler": "Tractr/headless-chrome-crawler-fork"`

Have a nice day.

**Comment by kulikalov** [comment] 2020-10-17 06:51
hey @simlevesque! Thanks for the suggestion! I've used it a while ago. Judging by the referenced thread, the issue has been resolved in puppeteer 1.8.0. I'm updating the puppeteer version to the latest v1 version: 1.20.0. So, should be resolved soon.

**Closed** 2020-10-26 05:09 UTC
Labels: bug
